FROM node

ARG env=development

# set working directory
RUN mkdir /usr/src/ourloop-ui
WORKDIR /usr/src/ourloop-ui

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/ourloop-ui/node_modules/.bin:$PATH

COPY package.json /usr/src/ourloop-ui/package.json
COPY yarn.lock /usr/src/ourloop-ui/yarn.lock

# install dependencies
RUN corepack enable
RUN yarn install

# add app
COPY . /usr/src/ourloop-ui

# nginx startup
ENTRYPOINT ["yarn", "run", "start"]
