export enum DI_CONSTANTS {
  MAIL_JET = 'MAIL_JET',
  AWS_TRANSLATION = 'AWS_TRANSLATION',
  GOOGLE_TRANSLATION = 'GOOGLE_TRANSLATION',
  LAMBDA = 'LAMBDA',
  GOOGLE_PLACES = 'GOOGLE_PLACES',
  GEO_IP = 'GEO_IP',
  GEOCODING = 'GEOCODING',
  CACHE = 'CACHE',
  CONFIG = 'CONFIG',
  AIRTABLE = 'AIRTABLE',
  CLIENT_PROXY = 'CLIENT_PROXY',
  TEXTIT = 'TEXTIT',
}
