# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - deploy

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

.deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  id_tokens:
    OIDC_TOKEN:
      aud: https://gitlab.com
  variables:
    AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/web_identity_token
  before_script:
    - echo "${OIDC_TOKEN}" > ${AWS_WEB_IDENTITY_TOKEN_FILE}
  script:
    - aws codepipeline start-pipeline-execution --name ${PIPELINE_NAME}

.deploy-dev:
  extends:
    - .deploy
  environment:
    name: dev

.deploy-staging:
  extends:
    - .deploy
  environment:
    name: staging

.deploy-production:
  extends:
    - .deploy
  environment:
    name: production

connection-tester-dev:
  variables:
    PIPELINE_NAME: ${CONNECTION_TESTER_PIPELINE_NAME}
  extends:
    - .deploy-dev
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      changes:
        - apps/connection_tester/**
  stage: deploy

lambda-create-challenge-dev:
  variables:
    PIPELINE_NAME: ${LAMBDA_CREATE_CHALLENGE_PIPELINE_NAME}
  extends:
    - .deploy-dev
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      changes:
        - lambdas/auth/create_challenge/**
  stage: deploy
