version: '3.8'

services:
  node-app:
    build:
      context: ./apps/inngest-service
      dockerfile: Dockerfile
    container_name: inngest-service
    ports:
      - "3000:3000"  # Change if your Node app uses a different port
    environment:
      - INNGEST_URL=http://inngest:8288
    depends_on:
      - inngest
    networks:
      - app-network

  inngest:
    build:
      context: ./apps/inngest-dashboard
      dockerfile: Dockerfile
    container_name: inngest
    ports:
      - "8288:8288"  # Default port for Inngest Dev Server
    environment:
      - INNGEST_DEV=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
