nodeLinker: node-modules
npmScopes:
  ourloop:
    # this should point at your GitLab npm registry endpoint:
    npmRegistryServer: "https://gitlab.com/api/v4/projects/24487110/packages/npm/"
    # optionally, if you store your token in env:
    npmAuthToken: "***REMOVED***"
