export enum CHANNEL_CONSTANTS {
  WEB = 'web',
  SMS = 'sms',
  MESSENGER = 'messenger',
  WHATSAPP = 'whatsapp',
  IVRR = 'ivrr',
  TELEGRAM = 'telegram',
}

export const CHANNEL_NUMBER_TO_CONSTANT: { [key: number]: CHANNEL_CONSTANTS } = {
  1: CHANNEL_CONSTANTS.SMS,
  2: CHANNEL_CONSTANTS.WEB,
  3: CHANNEL_CONSTANTS.WHATSAPP,
  4: CHANNEL_CONSTANTS.MESSENGER,
  5: CHANNEL_CONSTANTS.TELEGRAM,
  6: CHANNEL_CONSTANTS.IVRR,
};