import { LANGUAGES_CONSTANTS } from './languages.constants';

export enum MANAGER_TEMPLATES {
  NEW_STORY_IN_CASE_MANAGER_SYSTEM = 3706722,
  UNANSWERED_STORIES = 4558400,
  URGENT_CASE = 6597568
}

export enum USER_TEMPLATES {
  REJECT_STORY = 'REJECT_STORY',
  PUBLISH_STORY = 'PUBLISH_STORY',
  REJECT_REPLY = 'REJECT_REPLY',
  PUBLISH_REPLY = 'PUBLISH_REPLY',
  YOUR_ORGANISATION_HAS_BEEN_TAGGED = 'YOUR_ORGANISATION_HAS_BEEN_TAGGED',
  COMMENT_WAS_PUBLISH_ON_OBSERVED_STORY = 'COMMENT_WAS_PUBLISH_ON_OBSERVED_STORY',
  USER_LINKED_TO_ORGANISATION = 'USER_LINKED_TO_ORGANISATION',
  USER_INVITED_TO_ORGANISATION = 'USER_INVITED_TO_ORGANISATION',
  USER_SUBSCRIPTON_TOKEN = 'USER_SUBSCRIPTON_TOKEN',
}

const MailTemplatesConstants = new Map([
  [
    LANGUAGES_CONSTANTS.ENGLISH,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 1598322],
      [USER_TEMPLATES.PUBLISH_STORY, 1598260],
      [USER_TEMPLATES.REJECT_REPLY, 1598351],
      [USER_TEMPLATES.PUBLISH_REPLY, 1598461],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 1598432],
      [USER_TEMPLATES.COMMENT_WAS_PUBLISH_ON_OBSERVED_STORY, 1598318],
      [USER_TEMPLATES.USER_LINKED_TO_ORGANISATION, 4874582],
      [USER_TEMPLATES.USER_INVITED_TO_ORGANISATION, 4918984],
      [USER_TEMPLATES.USER_SUBSCRIPTON_TOKEN, 4959865],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.RUSSIAN,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 5525090],
      [USER_TEMPLATES.PUBLISH_STORY, 5525078],
      [USER_TEMPLATES.REJECT_REPLY, 5525066],
      [USER_TEMPLATES.PUBLISH_REPLY, 5524976],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 5524963],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.ARABIC,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 2946931],
      [USER_TEMPLATES.PUBLISH_STORY, 2946906],
      [USER_TEMPLATES.REJECT_REPLY, 2946952],
      [USER_TEMPLATES.PUBLISH_REPLY, 2946948],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 2946965],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.BEMBA,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 2946997],
      [USER_TEMPLATES.PUBLISH_STORY, 2946990],
      [USER_TEMPLATES.REJECT_REPLY, 2947005],
      [USER_TEMPLATES.PUBLISH_REPLY, 2947256],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 2946982],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.FRENCH,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 2947016],
      [USER_TEMPLATES.PUBLISH_STORY, 2947011],
      [USER_TEMPLATES.REJECT_REPLY, 2947010],
      [USER_TEMPLATES.PUBLISH_REPLY, 2947019],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 2947022],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.SOMALI || LANGUAGES_CONSTANTS.BARAWANI || LANGUAGES_CONSTANTS.BANADIRI || LANGUAGES_CONSTANTS.BAAJUUNI,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 2947351],
      [USER_TEMPLATES.PUBLISH_STORY, 2947307],
      [USER_TEMPLATES.REJECT_REPLY, 2947378],
      [USER_TEMPLATES.PUBLISH_REPLY, 2947420],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 2947439],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.SPANISH,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 2947598],
      [USER_TEMPLATES.PUBLISH_STORY, 2947570],
      [USER_TEMPLATES.REJECT_REPLY, 2947534],
      [USER_TEMPLATES.PUBLISH_REPLY, 2947505],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 2947483],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.NYANJA,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 2947715],
      [USER_TEMPLATES.PUBLISH_STORY, 2947745],
      [USER_TEMPLATES.REJECT_REPLY, 2947773],
      [USER_TEMPLATES.PUBLISH_REPLY, 2947883],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 2947911],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.TAGALOG,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 2948070],
      [USER_TEMPLATES.PUBLISH_STORY, 2948044],
      [USER_TEMPLATES.REJECT_REPLY, 2948010],
      [USER_TEMPLATES.PUBLISH_REPLY, 2947989],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 2947962],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.MAAY,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 3137899],
      [USER_TEMPLATES.PUBLISH_STORY, 3137919],
      [USER_TEMPLATES.REJECT_REPLY, 3137934],
      [USER_TEMPLATES.PUBLISH_REPLY, 3137929],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 3137949],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.INDONESIAN,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 3137989],
      [USER_TEMPLATES.PUBLISH_STORY, 3138019],
      [USER_TEMPLATES.REJECT_REPLY, 3138057],
      [USER_TEMPLATES.PUBLISH_REPLY, 3138032],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 3138061],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.TONGA,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 3239378],
      [USER_TEMPLATES.PUBLISH_STORY, 3239400],
      [USER_TEMPLATES.REJECT_REPLY, 3239408],
      [USER_TEMPLATES.PUBLISH_REPLY, 3239421],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 3239450],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.LOZI,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 3641449],
      [USER_TEMPLATES.PUBLISH_STORY, 3641456],
      [USER_TEMPLATES.REJECT_REPLY, 3641452],
      [USER_TEMPLATES.PUBLISH_REPLY, 3641445],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 3641451],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.CEBUANO,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 3641784],
      [USER_TEMPLATES.PUBLISH_STORY, 3641790],
      [USER_TEMPLATES.REJECT_REPLY, 3641787],
      [USER_TEMPLATES.PUBLISH_REPLY, 3641781],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 3641785],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.UKRAINIAN,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 3743564],
      [USER_TEMPLATES.PUBLISH_STORY, 3743598],
      [USER_TEMPLATES.REJECT_REPLY, 3743587],
      [USER_TEMPLATES.PUBLISH_REPLY, 3743606],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 3743572],
    ]),
  ],
  [
    LANGUAGES_CONSTANTS.POLISH,
    new Map([
      [USER_TEMPLATES.REJECT_STORY, 3750995],
      [USER_TEMPLATES.PUBLISH_STORY, 3750988],
      [USER_TEMPLATES.REJECT_REPLY, 3750989],
      [USER_TEMPLATES.PUBLISH_REPLY, 3750986],
      [USER_TEMPLATES.YOUR_ORGANISATION_HAS_BEEN_TAGGED, 3750991],
      [USER_TEMPLATES.COMMENT_WAS_PUBLISH_ON_OBSERVED_STORY, 3804151],
    ]),
  ],
]);

export const getMailTemplateId = (language: string, code: string): number => {
  const languages: string[] = Object.values(LANGUAGES_CONSTANTS);

  if (!languages.includes(language as LANGUAGES_CONSTANTS)) {
    language = LANGUAGES_CONSTANTS.ENGLISH;
  }

  const templateId = MailTemplatesConstants.get(
    language as LANGUAGES_CONSTANTS,
  )?.get(code as USER_TEMPLATES);

  if (!templateId) {
    return MailTemplatesConstants.get(LANGUAGES_CONSTANTS.ENGLISH).get(
      code as USER_TEMPLATES,
    );
  }

  return templateId;
};
