export enum LANGUAGES_CONSTANTS {
  ENGLISH = 'en',
  FRENCH = 'fr',
  SPANISH = 'es',
  ARABIC = 'ar',
  NYANJA = 'ny',
  CEBUANO = 'ceb',
  SOMALI = 'so',
  TAGALOG = 'tl',
  BEMBA = 'bem',
  MAAY = 'maa',
  INDONESIAN = 'id',
  TONGA = 'tog',
  UKRAINIAN = 'uk',
  POLISH = 'pl',
  LOZI = 'loz',
  RUSSIAN = 'ru',
  BAAJUUNI = 'bju',
  BANADIRI = 'bnd',
  BARAWANI = 'bara',
  KIZIGUA = 'kiz',
  SWAHILI = 'sw',
}

export const LANGUAGE_NAMES = {
  1: "English",
  3: "French",
  4: "Spanish",
  5: "Arabic",
  6: "Chichewa",
  7: "Somali (Maxatiri)",
  8: "N/A", // unknown cew language
  9: "Tagalog",
  10: "Bemba",
  11: "Cebuano",
  12: "Somali (af Maay)",
  13: "Bahasa Indonesia",
  14: "Tonga",
  15: "Lozi",
  16: "Ukrainian",
  17: "Polski",
  18: "Nederlands",
  19: "Lietuvių",
  20: "Deutsch",
  21: "Russian",
  22: "Somali (Baajuuni)",
  23: "Somali (Banadiri-Marka)",
  24: "Somali (Barawani-Chimini)",
  25: "Somali (Kizigua)",
  26: "Swahili",
};