NODE_ENV=development
DB_USERNAME=root
DB_PASSWORD=root
DB_DATABASE=loop
DB_HOST=localhost
DB_PORT=3307
FRONTEND_URL=http://localhost
BACKEND_URL=http://localhost
GLOBAL_PREFIX=api/v1
COGNITO_ACCESS_KEY_ID=
COGNITO_SECRET_ACCESS_KEY=
COGNITO_USER_POOL_ID=
COGNITO_CLIENT_ID=
COGNITO_REGION=ap-southeast-1
DISABLE_NOTIFICATIONS=false
MAILJET_API_KEY=
MAILJET_API_SECRET=
MAILJET_EMAIL=no-reply@ourloop.io
MAILJET_USERNAME=OurLoop.io
ROLLBAR_ACCESS_TOKEN=
REDIS_HOST=0.0.0.0
REDIS_SCHEMA=
REDIS_USER=
REDIS_PORT=6379
REDIS_PASSWORD=redis_password
APP_PORT=5000
COMMUNICATION_TIMEOUT=5000
SUPPORT_EMAIL=

TRANSLATION_ACCESS_KEY_ID=
TRANSLATION_SECRET_ACCESS_KEY=
TRANSLATION_REGION=ap-southeast-1
TRANSLATION_MINIMUM_PROBABILITY=70
TRANSLATE_FUNCTION_ARN=
TRANSLATE_FUNCTION_NAME=
TRANSCRIBE_FUNCTION_ARN=

GOOGLE_TRANSLATION_PROJECT_ID=ourloop
GOOGLE_TRANSLATION_LOCATION=global
GOOGLE_CREDENTIALS=
GOOGLE_LOCATIONS_API_KEY=

AIRTABLE_APIKEY=
AIRTABLE_SENSITIVE_CASES_BASE=
AIRTABLE_DASHBOARD_BASE=
BASIC_TOKEN=

AWS_ACCESS_KEY=
AWS_SECRET_KEY=
AWS_REGION=eu-central-1
AWS_S3_BUCKET=ivrr-development

# Inngest (gateway mounts /api/inngest when both are set)
INNGEST_SIGNING_KEY=
INNGEST_EVENT_KEY=

# Metabase static embedding (override to match your Metabase base URL + embedding secret)
METABASE_SITE_URL=http://localhost:3000
METABASE_SECRET_KEY=

# Azure Speech — used by Inngest transcribe worker
AZURE_SPEECH_KEY=
# Optional JSON array, e.g. ["so-SO"]
AZURE_TRANSCRIBE_LANGUAGES=
