image: 'public.ecr.aws/bitnami/node:16'

stages:
  - install
  - dependencies
  - build
  - test
  - deploy

check:
  only:
    - merge_requests
  stage: dependencies
  script:
    - yarn install
    - yarn check:dependencies
  dependencies:
    - install

install:
  stage: install
  only:
    - merge_requests
  script:
    - npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set -- //gitlab.com/api/v4/projects/24487110/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set @ourloop:registry https://gitlab.com/api/v4/packages/npm/
    - rm -rf node_modules
    - yarn install
  artifacts:
    name: 'artifacts-$CI_PIPELINE_ID'
    expire_in: 30 minutes
    paths:
      - node_modules/
      - .npmrc

build:
  stage: build
  only:
    - merge_requests
  script:
    - yarn install
    - yarn build-ci
  dependencies:
    - install

audit:
  only:
    - merge_requests
  stage: dependencies
  script:
    - yarn audit

lint:
  only:
    - merge_requests
  stage: test
  script:
    - yarn install
    - yarn lint
  dependencies:
    - install

unit-test:
  only:
    - merge_requests
  stage: test
  script:
    - yarn install
    - yarn test --coverage
  dependencies:
    - install
  artifacts:
    name: 'cov-artifact-$CI_PIPELINE_ID'
    expire_in: 1 day
    paths:
      - ./coverage

e2e-tests:
  only:
    - merge_requests
  stage: test
  cache:
    key: $CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  variables:
    NODE_ENV: development
    REDIS_HOST: redis
    REDIS_PASSWORD: ''
    REDIS_PORT: 6379
    ROLLBAR_ACCESS_TOKEN: $ROLLBAR_ACCESS_TOKEN
  services:
    - name: redis:5.0.7
      alias: redis
    - name: mysql:8.0.20
      alias: db
      entrypoint:
        [
          '/entrypoint.sh',
          '--default-authentication-plugin=mysql_native_password',
        ]
  script:
    - yarn test:integration
  dependencies:
    - install

deploy_production:
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - apt-get update -qy && apt-get install jq openssh-client -qqy
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  only:
    variables:
      - $CI_COMMIT_TITLE =~ /^Merge branch (.*) 'deploy-production'/
  stage: deploy
  script:
    - git remote add awscommit https://$(echo $CODE_COMMIT_KEY | base64 -d)@git-codecommit.eu-central-1.amazonaws.com/v1/repos/ourloop-ivrrbot
    - git push awscommit HEAD:refs/heads/production --force
    - git push awscommit --tags --force
  dependencies:
    - unit-test

deploy_staging:
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - apt-get update -qy && apt-get install jq openssh-client -qqy
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  only:
    variables:
      - $CI_COMMIT_TITLE =~ /^Merge branch (.*) 'deploy-staging'/
  stage: deploy
  script:
    - git remote add awscommit https://$(echo $CODE_COMMIT_KEY | base64 -d)@git-codecommit.eu-central-1.amazonaws.com/v1/repos/ourloop-ivrrbot
    - git push awscommit HEAD:refs/heads/staging --force
    - git push awscommit --tags --force
  dependencies:
    - unit-test

deploy_dev:
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - apt-get update -qy && apt-get install jq openssh-client -qqy
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  only:
    variables:
      - $CI_COMMIT_TITLE =~ /^Merge branch (.*) 'deploy-develop'/
  stage: deploy
  script:
    - git remote add awscommit https://$(echo $CODE_COMMIT_KEY | base64 -d)@git-codecommit.eu-central-1.amazonaws.com/v1/repos/ourloop-ivrrbot
    - git push awscommit HEAD:refs/heads/develop --force
    - git push awscommit --tags --force
  dependencies:
    - unit-test

deploy_to_development:
  only:
    variables:
      - $CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "web"
  stage: deploy
  script:
    - git status
    - git remote add awscommit https://$(echo $CODE_COMMIT_KEY | base64 -d)@git-codecommit.eu-central-1.amazonaws.com/v1/repos/ourloop-ivrrbot
    - git push awscommit HEAD:refs/heads/develop --force
    - git push awscommit --tags --force

deploy_to_staging:
  only:
    variables:
      - $CI_COMMIT_BRANCH == "staging" && $CI_PIPELINE_SOURCE == "web"
  stage: deploy
  script:
    - git status
    - git remote add awscommit https://$(echo $CODE_COMMIT_KEY | base64 -d)@git-codecommit.eu-central-1.amazonaws.com/v1/repos/ourloop-ivrrbot
    - git push awscommit HEAD:refs/heads/staging --force
    - git push awscommit --tags --force

deploy_to_production:
  only:
    variables:
      - $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"
  stage: deploy
  script:
    - git status
    - git remote add awscommit https://$(echo $CODE_COMMIT_KEY | base64 -d)@git-codecommit.eu-central-1.amazonaws.com/v1/repos/ourloop-ivrrbot
    - git push awscommit HEAD:refs/heads/production --force
    - git push awscommit --tags --force

deploy_anything:
  only:
    variables:
      - $CI_COMMIT_BRANCH != "develop" && $CI_COMMIT_BRANCH != "master" && $CI_COMMIT_BRANCH != "staging" && $CI_PIPELINE_SOURCE == "web"
  stage: deploy
  script:
    - git status
    - git remote add awscommit https://$(echo $CODE_COMMIT_KEY | base64 -d)@git-codecommit.eu-central-1.amazonaws.com/v1/repos/ourloop-ivrrbot
    - git push awscommit HEAD:refs/heads/develop --force
    - git push awscommit --tags --force
