FROM node:14.1.0

RUN apt-get update && apt-get install -y \
       nano \
       build-essential \
       libssl-dev

RUN mkdir -p /app

COPY . /var/www/backend
WORKDIR /var/www/backend

RUN ls
RUN pwd

EXPOSE 5002

ENV DOCKERIZE_VERSION v0.6.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

CMD rm -rf /node_modules && npm install && npm run start:dev
