FROM public.ecr.aws/docker/library/node:20-alpine3.17

# Install system dependencies
RUN apk add --no-cache build-base libssl1.1 jq python3 py3-pip py3-setuptools groff less bash

# Update pip and install awscli
RUN pip3 install --no-cache-dir --upgrade pip awscli \
    && rm -rf /var/cache/apk/*

RUN mkdir -p /var/www/backend

# Copy app files
WORKDIR /var/www/backend
COPY src /var/www/backend/src
COPY storage /var/www/backend/storage
COPY types /var/www/backend/types
COPY tsconfig.build.json /var/www/backend
COPY tsconfig.json /var/www/backend
COPY package.json /var/www/backend
COPY entrypoint_local.sh /var/www/backend

RUN chmod +x /var/www/backend/entrypoint_local.sh

# Set environment variables
ARG NPM_TOKEN
ENV ENV_NPM_TOKEN=$NPM_TOKEN
RUN env
RUN npm config set @ourloop:registry https://gitlab.com/api/v4/packages/npm/
RUN npm config set '//gitlab.com/api/v4/packages/npm/:_authToken' $ENV_NPM_TOKEN
RUN npm config set '//gitlab.com/api/v4/projects/24487110/packages/npm/:_authToken' $ENV_NPM_TOKEN

# Install app dependencies
RUN yarn install --non-interactive --verbose \
    && yarn cache clean
# Expose port and run entrypoint
EXPOSE 5000

ENTRYPOINT ["/var/www/backend/entrypoint_local.sh"]

CMD ["yarn", "run", "start:dev"]
