/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { TalkToLoopClient } from './TalkToLoopClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AddCommentDto } from './models/AddCommentDto';
export type { AddOrganisationApplicationDto } from './models/AddOrganisationApplicationDto';
export type { AddStoryDto } from './models/AddStoryDto';
export type { AdministrativeDataPathRO } from './models/AdministrativeDataPathRO';
export type { AdministrativeDataRO } from './models/AdministrativeDataRO';
export type { AirTableSyncAllegationReferralDTO } from './models/AirTableSyncAllegationReferralDTO';
export type { AirTableSyncAllegationReferralOrganisationDTO } from './models/AirTableSyncAllegationReferralOrganisationDTO';
export type { AirTableSyncDTO } from './models/AirTableSyncDTO';
export type { AirTableSyncInvestigationDTO } from './models/AirTableSyncInvestigationDTO';
export type { AverageTakenTimeToCompleteStepItemRO } from './models/AverageTakenTimeToCompleteStepItemRO';
export type { AverageTakenTimeToCompleteStepRO } from './models/AverageTakenTimeToCompleteStepRO';
export type { AverageTakenTimeToCompleteStepTooltipRO } from './models/AverageTakenTimeToCompleteStepTooltipRO';
export type { AvgResponseTimePerStoryTypeRO } from './models/AvgResponseTimePerStoryTypeRO';
export type { CallRO } from './models/CallRO';
export type { CaseManagerRO } from './models/CaseManagerRO';
export type { CategoryRO } from './models/CategoryRO';
export type { checkTranslationDto } from './models/checkTranslationDto';
export type { CheckTranslationRO } from './models/CheckTranslationRO';
export type { CommentListModeratorPaginationRO } from './models/CommentListModeratorPaginationRO';
export type { CommentListModeratorRO } from './models/CommentListModeratorRO';
export type { CommentModeratorRO } from './models/CommentModeratorRO';
export type { CommentStoryListRO } from './models/CommentStoryListRO';
export type { ConsentsDto } from './models/ConsentsDto';
export type { CountRO } from './models/CountRO';
export type { CountryByIpRO } from './models/CountryByIpRO';
export type { CountryRO } from './models/CountryRO';
export type { CreateOrganisationDto } from './models/CreateOrganisationDto';
export type { DeleteCasesDTO } from './models/DeleteCasesDTO';
export type { EditUserDataDto } from './models/EditUserDataDto';
export type { EditUserNotificationDto } from './models/EditUserNotificationDto';
export type { ExportedStoriesWithPaginationRO } from './models/ExportedStoriesWithPaginationRO';
export type { ExportedStoryRO } from './models/ExportedStoryRO';
export type { ExportStoriesDTO } from './models/ExportStoriesDTO';
export type { ExportStoryDto } from './models/ExportStoryDto';
export type { FinishedTextItFlowDTO } from './models/FinishedTextItFlowDTO';
export type { GenerateTokenDTO } from './models/GenerateTokenDTO';
export type { HowManyCaseReceivedRO } from './models/HowManyCaseReceivedRO';
export type { IdRo } from './models/IdRo';
export type { IdWithCounterRO } from './models/IdWithCounterRO';
export type { IncomingStoriesAndCommentsRO } from './models/IncomingStoriesAndCommentsRO';
export type { LanguageRO } from './models/LanguageRO';
export type { LexiconRO } from './models/LexiconRO';
export type { LinkedUsersToOrganisationsRO } from './models/LinkedUsersToOrganisationsRO';
export type { LinkUsersToOrganisationsDTO } from './models/LinkUsersToOrganisationsDTO';
export type { LinkUserToOrganisationDTO } from './models/LinkUserToOrganisationDTO';
export type { LocationRO } from './models/LocationRO';
export type { MessageRO } from './models/MessageRO';
export type { MessengerAvailabilityRO } from './models/MessengerAvailabilityRO';
export type { MessengerFlowRequestDto } from './models/MessengerFlowRequestDto';
export type { MessengerUserRequestDto } from './models/MessengerUserRequestDto';
export type { OrganisationRO } from './models/OrganisationRO';
export type { OrganisationStoriesRO } from './models/OrganisationStoriesRO';
export type { OutgoingCommentsRO } from './models/OutgoingCommentsRO';
export type { PaginationRO } from './models/PaginationRO';
export type { PhoneAvailabilityRO } from './models/PhoneAvailabilityRO';
export type { RecordingRO } from './models/RecordingRO';
export type { RecordingsRO } from './models/RecordingsRO';
export type { RejectContentDto } from './models/RejectContentDto';
export type { RejectContentWithStoryDto } from './models/RejectContentWithStoryDto';
export type { RejectedStoriesRO } from './models/RejectedStoriesRO';
export type { RejectStoriesDto } from './models/RejectStoriesDto';
export type { RemoveCommentTranslationDto } from './models/RemoveCommentTranslationDto';
export type { RemoveStoryTranslationDto } from './models/RemoveStoryTranslationDto';
export type { ResponsiveByStepRO } from './models/ResponsiveByStepRO';
export type { RetryTranslationDto } from './models/RetryTranslationDto';
export type { SaveIvrrCallDto } from './models/SaveIvrrCallDto';
export type { SaveIvrrStoryDto } from './models/SaveIvrrStoryDto';
export type { SaveTranslationDto } from './models/SaveTranslationDto';
export type { SearchResultItemRO } from './models/SearchResultItemRO';
export type { SearchResultRO } from './models/SearchResultRO';
export type { SendCommentDto } from './models/SendCommentDto';
export type { SenderRO } from './models/SenderRO';
export type { sendInvitationToUserDTO } from './models/sendInvitationToUserDTO';
export type { SendMessageDto } from './models/SendMessageDto';
export type { SendMessageRO } from './models/SendMessageRO';
export type { SendMessageToSupportDto } from './models/SendMessageToSupportDto';
export type { SendTokenDTO } from './models/SendTokenDTO';
export type { SetCommentAsPublishedDto } from './models/SetCommentAsPublishedDto';
export type { SMSConversationModel } from './models/SMSConversationModel';
export type { StatusRO } from './models/StatusRO';
export type { StoriesAndRepliesGroupedByCategoryRO } from './models/StoriesAndRepliesGroupedByCategoryRO';
export type { StoriesAuthorPerAgeAndGenderRO } from './models/StoriesAuthorPerAgeAndGenderRO';
export type { StoriesCodeDatesRO } from './models/StoriesCodeDatesRO';
export type { StoriesCodeValuesRO } from './models/StoriesCodeValuesRO';
export type { StoriesDividedByDisabilityRO } from './models/StoriesDividedByDisabilityRO';
export type { StoriesTypeAndRepliesRO } from './models/StoriesTypeAndRepliesRO';
export type { StoryIvrrModeratorRO } from './models/StoryIvrrModeratorRO';
export type { StoryListModeratorPaginationRO } from './models/StoryListModeratorPaginationRO';
export type { StoryListModeratorRO } from './models/StoryListModeratorRO';
export type { StoryListPaginationRO } from './models/StoryListPaginationRO';
export type { StoryListRO } from './models/StoryListRO';
export type { StoryMessengerModeratorRO } from './models/StoryMessengerModeratorRO';
export type { StoryRO } from './models/StoryRO';
export type { StorySMSModeratorRO } from './models/StorySMSModeratorRO';
export type { StoryWebModeratorRO } from './models/StoryWebModeratorRO';
export type { SubscriptionAccessDTO } from './models/SubscriptionAccessDTO';
export type { SubscriptionTokenRO } from './models/SubscriptionTokenRO';
export type { SuccessRO } from './models/SuccessRO';
export type { TextItIngoingMessageDTO } from './models/TextItIngoingMessageDTO';
export type { TextItOutgoingMessageDto } from './models/TextItOutgoingMessageDto';
export type { ThematicRO } from './models/ThematicRO';
export type { TranscribeHistoricalStoriesDto } from './models/TranscribeHistoricalStoriesDto';
export type { TranslationDto } from './models/TranslationDto';
export type { TranslationRO } from './models/TranslationRO';
export type { TwilioAudioDto } from './models/TwilioAudioDto';
export type { TypeAverageCountRO } from './models/TypeAverageCountRO';
export type { TypeValuesRO } from './models/TypeValuesRO';
export type { UpdateCommentCommentDTO } from './models/UpdateCommentCommentDTO';
export type { UpdateIvrrCallFlowDto } from './models/UpdateIvrrCallFlowDto';
export type { UpdateStoryDto } from './models/UpdateStoryDto';
export type { UploadedFilesRO } from './models/UploadedFilesRO';
export type { UserCommentDetailsRO } from './models/UserCommentDetailsRO';
export type { UserOrganisationRO } from './models/UserOrganisationRO';
export type { UserProfileRO } from './models/UserProfileRO';
export type { UserResponseDto } from './models/UserResponseDto';
export type { VerifyCommentTranslationDto } from './models/VerifyCommentTranslationDto';
export type { VerifyStoryTranslationDto } from './models/VerifyStoryTranslationDto';
export type { WhatAreTheOutcomesRO } from './models/WhatAreTheOutcomesRO';

export { AdministrativeDataService } from './services/AdministrativeDataService';
export { AgeService } from './services/AgeService';
export { AirTableSyncService } from './services/AirTableSyncService';
export { AuthService } from './services/AuthService';
export { CaseManagerService } from './services/CaseManagerService';
export { CategoryService } from './services/CategoryService';
export { CommentService } from './services/CommentService';
export { CommentModeratorService } from './services/CommentModeratorService';
export { CommentTranslationModeratorService } from './services/CommentTranslationModeratorService';
export { CountryService } from './services/CountryService';
export { DashboardService } from './services/DashboardService';
export { DifficultyService } from './services/DifficultyService';
export { GenderService } from './services/GenderService';
export { IvrrService } from './services/IvrrService';
export { IvrrStoryModeratorService } from './services/IvrrStoryModeratorService';
export { LanguageService } from './services/LanguageService';
export { MaternityStatusService } from './services/MaternityStatusService';
export { MessengerService } from './services/MessengerService';
export { OrganisationService } from './services/OrganisationService';
export { RejectReasonService } from './services/RejectReasonService';
export { SmsService } from './services/SmsService';
export { SortingService } from './services/SortingService';
export { StatisticCasesService } from './services/StatisticCasesService';
export { StatisticFiltersForCasesService } from './services/StatisticFiltersForCasesService';
export { StatisticOpenService } from './services/StatisticOpenService';
export { StoryService } from './services/StoryService';
export { StoryExportService } from './services/StoryExportService';
export { StoryModeratorService } from './services/StoryModeratorService';
export { StoryTranslationModeratorService } from './services/StoryTranslationModeratorService';
export { SubscriptionService } from './services/SubscriptionService';
export { TelegramService } from './services/TelegramService';
export { ThematicService } from './services/ThematicService';
export { UserService } from './services/UserService';
export { UserApplicationsService } from './services/UserApplicationsService';
export { WhatsAppService } from './services/WhatsAppService';
