FROM public.ecr.aws/docker/library/node:18-alpine3.17

# Install system dependencies
RUN apk add --no-cache build-base libssl1.1 jq python3 py3-pip py3-setuptools groff less bash

# Update pip and install awscli
RUN pip3 install --no-cache-dir --upgrade pip awscli \
    && rm -rf /var/cache/apk/*

RUN mkdir -p /app

# Copy app files
WORKDIR /var/www/backend
COPY src /var/www/backend/src
COPY tsconfig.build.json /var/www/backend
COPY tsconfig.json /var/www/backend
COPY package.json /var/www/backend
# Set environment variables
ARG NPM_TOKEN
ENV ENV_NPM_TOKEN=$NPM_TOKEN
RUN env
RUN npm config set @ourloop:registry https://gitlab.com/api/v4/packages/npm/
RUN npm config set '//gitlab.com/api/v4/packages/npm/:_authToken' $ENV_NPM_TOKEN
RUN npm config set '//gitlab.com/api/v4/projects/24487110/packages/npm/:_authToken' $ENV_NPM_TOKEN

# Install app dependencies
RUN yarn install --non-interactive --verbose \
    && yarn cache clean

CMD ["yarn", "run", "start:dev"]