export enum STORY_STATUS {
  NOT_STARTED = 'not_started',
  PENDING_TRANSLATION = 'pending_translation',
  AWAITING_REPLAY = 'awaiting_replay',
  ISSUER_REPLIED = 'issuer_replied',
  ISSUER_DID_NOT_REPLIED = 'issuer_did_not_replied',
  SENT_FROM_CASE_MANAGER_TO_LOOP = 'sent_from_case_manager_to_loop',
  PENDING_TRANSCRIPTION = 'pending_transcription',
  TRANSCRIPTION_IN_PROGRESS = 'transcription_in_progress',
  TRANSCRIPTION_FAILED = 'transcription_failed',
  PENDING_PUBLICATION = 'pending_publication',
  PUBLISHED = 'published',
  REJECTED = 'rejected',
  SENT_TO_CASE_MANAGER = 'sent_to_case_manager',
}
