import * as Joi from 'joi';

export const configSchema: Joi.ObjectSchema = Joi.object({
  NODE_ENV: Joi.string(),
  GLOBAL_PREFIX: Joi.string(),
  ROLLBAR_ACCESS_TOKEN: Joi.string(),
  REDIS_HOST: Joi.string(),
  REDIS_USER: Joi.string(),
  REDIS_PORT: Joi.string(),
  REDIS_PASSWORD: Joi.string(),
  REDIS_SCHEMA: Joi.string(),
  APP_PORT: Joi.string(),
  FLOW_TTL: Joi.string().optional(),
  PROCESS_CALL_DELAY: Joi.string().optional(),
  COMMUNICATION_TIMEOUT: Joi.string().optional(),
  TWILIO_ACCSID: Joi.string(),
  TWILIO_AUTH_TOKEN: Joi.string(),
  TWILIO_PHONE_NUMBERS: Joi.string(),
  AWS_REGION: Joi.string(),
  AWS_S3_BUCKET: Joi.string(),
  IVRR_SERVICE_URL: Joi.string(),
  SCHEDULER_DIFF_IN_HOURS: Joi.string().optional(),
  START_NIGHT_HOUR: Joi.string().optional(),
  END_NIGHT_HOUR: Joi.string().optional(),
  MINIMUM_PERCENTAGE_HEARD_LEVEL: Joi.string().optional(),
  BASIC_TOKEN: Joi.string(),
}).options({ allowUnknown: true, presence: 'required' });
