export enum SENSITIVE_STORY_COLUMNS {
  CONTENT = 'Story 🔒',
  CONTENT_ENG = 'Story ENG 🔒',
  ORGANIZATION = 'Tagged organisation',
  LANGUAGE = 'Original language',
  COUNTRY = 'Country',
  GENDER = 'Author Gender',
  AGE = 'Author Age',
  LOOP_ID = 'Loop ID',
  PHONE = 'Cell phone',
  EMAIL = 'Email',
  DISABILITY = 'Disability',
  CATEGORY = 'Thematic Area',
  SUBCATEGORY = 'Thematic Area - Subsection',
  MODERATOR_NOTE = 'Note from moderator 🔒',
  URGENCY = 'Urgency',
  LOCATION = 'Location',
  MARKED_AS_SENSITIVE_BY = 'Tagged sensitive by 🔒',
  AUTHOR_ALLOWED_FOR_CONTACT = 'Author allowed for contact',
}
