export enum CHANNEL_CONSTANTS {
  WEB = 'web',
  SMS = 'sms',
  MESSENGER = 'messenger',
  WHATSAPP = 'whatsapp',
  TELEGRAM = 'telegram',
  IVRR = 'ivrr',
  TEXT = 'text',
}

export const TEXT_CHANNELS = [
  CHANNEL_CONSTANTS.MESSENGER,
  CHANNEL_CONSTANTS.SMS,
  CHANNEL_CONSTANTS.TELEGRAM,
  CHANNEL_CONSTANTS.WEB,
  CHANNEL_CONSTANTS.WHATSAPP,
  CHANNEL_CONSTANTS.TEXT,
];
