import * as Joi from 'joi';

export const configSchema: Joi.ObjectSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'stage', 'test', 'local')
    .default('development'),
  DB_USERNAME: Joi.string(),
  DB_PASSWORD: Joi.string(),
  DB_HOST: Joi.string(),
  DB_PORT: Joi.string().default(3306),
  LANDING_PAGE_URL: Joi.string(),
  FRONTEND_URL: Joi.string(),
  BACKEND_URL: Joi.string(),
  GLOBAL_PREFIX: Joi.string(),
  COGNITO_USER_POOL_ID: Joi.string(),
  COGNITO_CLIENT_ID: Joi.string(),
  ANONYMIZE_CHARTS: Joi.string(),
  DISABLE_NOTIFICATIONS: Joi.string(),
  DISABLE_IVR_PUBLICATION_NOTIFICATIONS: Joi.string(),
  DISABLE_IVR_REJECT_NOTIFICATIONS: Joi.string(),
  MAILJET_API_KEY: Joi.string(),
  MAILJET_API_SECRET: Joi.string(),
  MAILJET_EMAIL: Joi.string(),
  MAILJET_USERNAME: Joi.string(),
  TRANSLATION_MINIMUM_PROBABILITY: Joi.string(),
  GOOGLE_TRANSLATION_PROJECT_ID: Joi.string(),
  GOOGLE_TRANSLATION_LOCATION: Joi.string(),
  REDIS_HOST: Joi.string(),
  REDIS_USER: Joi.string(),
  REDIS_PORT: Joi.string(),
  REDIS_PASSWORD: Joi.string(),
  REDIS_SCHEMA: Joi.string(),
  AIRTABLE_APIKEY: Joi.string(),
  AIRTABLE_DISABLE_SYNC: Joi.string().optional(),
  AIRTABLE_SENSITIVE_CASES_BASE: Joi.string(),
  AIRTABLE_DASHBOARD_BASE: Joi.string(),
  BASIC_TOKEN: Joi.string(),
  AWS_ACCESS_KEY: Joi.string().optional(),
  AWS_SECRET_KEY: Joi.string().optional(),
  AWS_S3_BUCKET: Joi.string(),
  AWS_REGION: Joi.string(),
  AZURE_SUBSCRIPTION_TOKEN: Joi.string(),
  ONLY_GET_REQUEST: Joi.string(),
  INNGEST_SIGNING_KEY: Joi.string(),
  INNGEST_EVENT_KEY: Joi.string(),
}).options({ allowUnknown: true, presence: 'required' });

