export enum TwilioTemplateKey {
  CHOOSE_LANG = 'CHOOSE_LANG',
  MORE_OPTIONS = 'MORE_OPTIONS',
  PUBLISH_CONSENT = 'PUBLISH_CONSENT',
  CONTACT_CONSENT = 'CONTACT_CONSENT',
  GET_STARTED = 'GET_STARTED',
  END_OF_SERVICE = 'END_OF_SERVICE_MODERATOR_FLOW'
} 