image: 'node:20.0.0'

stages:
  - install
  - dependencies
  - build
  - test
  - deploy

check:
  only:
    - merge_requests
  stage: dependencies
  script:
    - cd service
    - npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set -- //gitlab.com/api/v4/projects/24487110/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set @ourloop:registry https://gitlab.com/api/v4/packages/npm/
    - yarn install
    - yarn check:dependencies
  dependencies:
    - install

install:
  stage: install
  only:
    - merge_requests
  script:
    - cd service
    - npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set -- //gitlab.com/api/v4/projects/24487110/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set @ourloop:registry https://gitlab.com/api/v4/packages/npm/
    - rm -rf node_modules
    - yarn install
  artifacts:
    name: 'artifacts-$CI_PIPELINE_ID'
    expire_in: 30 minutes
    paths:
      - node_modules/
      - .npmrc

build:
  stage: build
  only:
    - merge_requests
  script:
    - cd service
    - npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set -- //gitlab.com/api/v4/projects/24487110/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set @ourloop:registry https://gitlab.com/api/v4/packages/npm/
    - yarn install
    - yarn build-ci
  dependencies:
    - install

audit:
  only:
    - merge_requests
  stage: dependencies
  script:
    - cd service
    - yarn audit

lint:
  only:
    - merge_requests
  stage: test
  script:
    - cd service
    - npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set -- //gitlab.com/api/v4/projects/24487110/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set @ourloop:registry https://gitlab.com/api/v4/packages/npm/
    - yarn install
    - yarn lint
  dependencies:
    - install

unit-test:
  only:
    - merge_requests
  stage: test
  script:
    - cd service
    - npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set -- //gitlab.com/api/v4/projects/24487110/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set @ourloop:registry https://gitlab.com/api/v4/packages/npm/
    - yarn install
    - yarn test --coverage
  dependencies:
    - install
  artifacts:
    name: 'cov-artifact-$CI_PIPELINE_ID'
    expire_in: 1 day
    paths:
      - ./coverage

e2e-tests:
  only:
    - merge_requests
  stage: test
  cache:
    key: $CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  variables:
    NODE_ENV: development
    REDIS_HOST: redis
    REDIS_PASSWORD: ''
    REDIS_PORT: 6379
    ROLLBAR_ACCESS_TOKEN: $ROLLBAR_ACCESS_TOKEN
  services:
    - name: redis:5.0.7
      alias: redis
    - name: mysql:8.0.20
      alias: db
      entrypoint:
        [
          '/entrypoint.sh',
          '--default-authentication-plugin=mysql_native_password',
        ]
  script:
    - cd service
    - npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set -- //gitlab.com/api/v4/projects/24487110/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set @ourloop:registry https://gitlab.com/api/v4/packages/npm/
    - yarn install
    - yarn test:integration
  dependencies:
    - install
